version: '3.5'

services:
  video:
    build: .
    volumes:
     - ./frames:/frames
     - ./download:/download
    environment:
      MONGO_URL: mongodb://root:example@192.168.99.100
      ELASTIC_URL: http://192.168.99.100:9200
      DOWNLOAD_DIR: /download
      FRAMES_DIR: /frames