version: '3.5'

services:
  notebook:
    image: jupyter/datascience-notebook
    container_name: jupyter
    ports:
     - 8888:8888
    volumes:
     - ../work:/home/jovyan/work
    environment:
      LC_CTYPE: en_US.UTF8
      JUPYTER_ALLOW_INSECURE_WRITES: 1
      JUPYTER_RUNTIME_DIR: "/tmp"